//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/benpapacek/Dev/kbignum/script/../kbignum-java/src/main/java/com/papacekb/kbignum/JBigDecimal.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComPapacekbKbignumJBigDecimal")
#ifdef RESTRICT_ComPapacekbKbignumJBigDecimal
#define INCLUDE_ALL_ComPapacekbKbignumJBigDecimal 0
#else
#define INCLUDE_ALL_ComPapacekbKbignumJBigDecimal 1
#endif
#undef RESTRICT_ComPapacekbKbignumJBigDecimal

#if !defined (ComPapacekbKbignumJBigDecimal_) && (INCLUDE_ALL_ComPapacekbKbignumJBigDecimal || defined(INCLUDE_ComPapacekbKbignumJBigDecimal))
#define ComPapacekbKbignumJBigDecimal_

@class ComPapacekbKbignumJBigInteger;
@class ComPapacekbKbignumJMathContext;
@class IOSObjectArray;

@interface ComPapacekbKbignumJBigDecimal : NSObject

#pragma mark Public

- (instancetype)initWithDouble:(jdouble)value;

- (instancetype)initWithLong:(jlong)value;

- (instancetype)initWithLong:(jlong)value
                     withInt:(jint)scale_;

- (instancetype)initWithNSString:(NSString *)value;

- (ComPapacekbKbignumJBigDecimal *)abs;

- (ComPapacekbKbignumJBigDecimal *)absWithComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)addWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)addWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                     withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (jbyte)byteValueExact;

- (jint)compareToWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)divideWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)divideWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                                                   withInt:(jint)scale_
                                                              withNSString:(NSString *)roundingMode;

- (ComPapacekbKbignumJBigDecimal *)divideWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                        withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)divideWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                                              withNSString:(NSString *)roundingMode;

- (IOSObjectArray *)divideAndRemainderWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (IOSObjectArray *)divideAndRemainderWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                     withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)divideToIntegralValueWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)divideToIntegralValueWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                                       withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)o;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jint)intValueExact;

- (jlong)longValue;

- (jlong)longValueExact;

- (ComPapacekbKbignumJBigDecimal *)maxWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)minWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)movePointLeftWithInt:(jint)n;

- (ComPapacekbKbignumJBigDecimal *)movePointRightWithInt:(jint)n;

- (ComPapacekbKbignumJBigDecimal *)multiplyWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)multiplyWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                          withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)negate;

- (ComPapacekbKbignumJBigDecimal *)negateWithComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)plus;

- (ComPapacekbKbignumJBigDecimal *)plusWithComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)powWithInt:(jint)n;

- (ComPapacekbKbignumJBigDecimal *)powWithInt:(jint)n
           withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (jint)precision;

- (ComPapacekbKbignumJBigDecimal *)remainderWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)remainderWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                           withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigDecimal *)roundWithComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (jint)scale__;

- (ComPapacekbKbignumJBigDecimal *)scaleByPowerOfTenWithInt:(jint)n;

- (ComPapacekbKbignumJBigDecimal *)setScaleWithInt:(jint)scale_;

- (ComPapacekbKbignumJBigDecimal *)setScaleWithInt:(jint)scale_
                                      withNSString:(NSString *)roundingMode;

- (jshort)shortValueExact;

- (jint)signum;

- (ComPapacekbKbignumJBigDecimal *)stripTrailingZeroes;

- (ComPapacekbKbignumJBigDecimal *)subtractWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n;

- (ComPapacekbKbignumJBigDecimal *)subtractWithComPapacekbKbignumJBigDecimal:(ComPapacekbKbignumJBigDecimal *)n
                                          withComPapacekbKbignumJMathContext:(ComPapacekbKbignumJMathContext *)mc;

- (ComPapacekbKbignumJBigInteger *)toBigInteger;

- (ComPapacekbKbignumJBigInteger *)toBigIntegerExact;

- (NSString *)toEngineeringString;

- (NSString *)toPlainString;

- (NSString *)description;

- (ComPapacekbKbignumJBigDecimal *)ulp;

- (ComPapacekbKbignumJBigInteger *)unscaledValue;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComPapacekbKbignumJBigDecimal)

FOUNDATION_EXPORT void ComPapacekbKbignumJBigDecimal_initWithNSString_(ComPapacekbKbignumJBigDecimal *self, NSString *value);

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *new_ComPapacekbKbignumJBigDecimal_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *create_ComPapacekbKbignumJBigDecimal_initWithNSString_(NSString *value);

FOUNDATION_EXPORT void ComPapacekbKbignumJBigDecimal_initWithDouble_(ComPapacekbKbignumJBigDecimal *self, jdouble value);

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *new_ComPapacekbKbignumJBigDecimal_initWithDouble_(jdouble value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *create_ComPapacekbKbignumJBigDecimal_initWithDouble_(jdouble value);

FOUNDATION_EXPORT void ComPapacekbKbignumJBigDecimal_initWithLong_(ComPapacekbKbignumJBigDecimal *self, jlong value);

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *new_ComPapacekbKbignumJBigDecimal_initWithLong_(jlong value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *create_ComPapacekbKbignumJBigDecimal_initWithLong_(jlong value);

FOUNDATION_EXPORT void ComPapacekbKbignumJBigDecimal_initWithLong_withInt_(ComPapacekbKbignumJBigDecimal *self, jlong value, jint scale_);

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *new_ComPapacekbKbignumJBigDecimal_initWithLong_withInt_(jlong value, jint scale_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJBigDecimal *create_ComPapacekbKbignumJBigDecimal_initWithLong_withInt_(jlong value, jint scale_);

J2OBJC_TYPE_LITERAL_HEADER(ComPapacekbKbignumJBigDecimal)

#endif

#pragma pop_macro("INCLUDE_ALL_ComPapacekbKbignumJBigDecimal")
