//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/benpapacek/Dev/kbignum/script/../kbignum-java/src/main/java/com/papacekb/kbignum/JByteArray.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComPapacekbKbignumJByteArray")
#ifdef RESTRICT_ComPapacekbKbignumJByteArray
#define INCLUDE_ALL_ComPapacekbKbignumJByteArray 0
#else
#define INCLUDE_ALL_ComPapacekbKbignumJByteArray 1
#endif
#undef RESTRICT_ComPapacekbKbignumJByteArray

#if !defined (ComPapacekbKbignumJByteArray_) && (INCLUDE_ALL_ComPapacekbKbignumJByteArray || defined(INCLUDE_ComPapacekbKbignumJByteArray))
#define ComPapacekbKbignumJByteArray_

@class IOSByteArray;

@interface ComPapacekbKbignumJByteArray : NSObject

#pragma mark Public

- (jbyte)getByteAtWithInt:(jint)index;

- (IOSByteArray *)getBytes;

- (jint)getSize;

#pragma mark Package-Private

- (instancetype)initWithByteArray:(IOSByteArray *)bytes;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComPapacekbKbignumJByteArray)

FOUNDATION_EXPORT void ComPapacekbKbignumJByteArray_initWithByteArray_(ComPapacekbKbignumJByteArray *self, IOSByteArray *bytes);

FOUNDATION_EXPORT ComPapacekbKbignumJByteArray *new_ComPapacekbKbignumJByteArray_initWithByteArray_(IOSByteArray *bytes) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJByteArray *create_ComPapacekbKbignumJByteArray_initWithByteArray_(IOSByteArray *bytes);

J2OBJC_TYPE_LITERAL_HEADER(ComPapacekbKbignumJByteArray)

#endif

#pragma pop_macro("INCLUDE_ALL_ComPapacekbKbignumJByteArray")
