//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/benpapacek/Dev/kbignum/script/../kbignum-java/src/main/java/com/papacekb/kbignum/JMathContext.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComPapacekbKbignumJMathContext")
#ifdef RESTRICT_ComPapacekbKbignumJMathContext
#define INCLUDE_ALL_ComPapacekbKbignumJMathContext 0
#else
#define INCLUDE_ALL_ComPapacekbKbignumJMathContext 1
#endif
#undef RESTRICT_ComPapacekbKbignumJMathContext

#if !defined (ComPapacekbKbignumJMathContext_) && (INCLUDE_ALL_ComPapacekbKbignumJMathContext || defined(INCLUDE_ComPapacekbKbignumJMathContext))
#define ComPapacekbKbignumJMathContext_

@class JavaMathMathContext;

@interface ComPapacekbKbignumJMathContext : NSObject {
 @public
  JavaMathMathContext *delegate_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)precision;

- (instancetype)initWithInt:(jint)precision
               withNSString:(NSString *)roundingMode;

- (instancetype)initWithJavaMathMathContext:(JavaMathMathContext *)delegate;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComPapacekbKbignumJMathContext)

J2OBJC_FIELD_SETTER(ComPapacekbKbignumJMathContext, delegate_, JavaMathMathContext *)

FOUNDATION_EXPORT void ComPapacekbKbignumJMathContext_initWithJavaMathMathContext_(ComPapacekbKbignumJMathContext *self, JavaMathMathContext *delegate);

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *new_ComPapacekbKbignumJMathContext_initWithJavaMathMathContext_(JavaMathMathContext *delegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *create_ComPapacekbKbignumJMathContext_initWithJavaMathMathContext_(JavaMathMathContext *delegate);

FOUNDATION_EXPORT void ComPapacekbKbignumJMathContext_initWithInt_(ComPapacekbKbignumJMathContext *self, jint precision);

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *new_ComPapacekbKbignumJMathContext_initWithInt_(jint precision) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *create_ComPapacekbKbignumJMathContext_initWithInt_(jint precision);

FOUNDATION_EXPORT void ComPapacekbKbignumJMathContext_initWithInt_withNSString_(ComPapacekbKbignumJMathContext *self, jint precision, NSString *roundingMode);

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *new_ComPapacekbKbignumJMathContext_initWithInt_withNSString_(jint precision, NSString *roundingMode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComPapacekbKbignumJMathContext *create_ComPapacekbKbignumJMathContext_initWithInt_withNSString_(jint precision, NSString *roundingMode);

J2OBJC_TYPE_LITERAL_HEADER(ComPapacekbKbignumJMathContext)

#endif

#pragma pop_macro("INCLUDE_ALL_ComPapacekbKbignumJMathContext")
